import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path'; import puppeteer from 'puppeteer-core';
const dist = path.resolve(import.meta.dirname, '..', 'dist');
const MIME = { '.html': 'text/html', '.css': 'text/css', '.js': 'text/javascript', '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml', '.webp': 'image/webp' };
const srv = http.createServer((req, res) => { const p = decodeURIComponent(req.url.split('?')[0]); let f = path.join(dist, p); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { const i = path.join(f, 'index.html'); f = fs.existsSync(i) ? i : path.join(dist, '404.html'); } res.writeHead(200, { 'content-type': MIME[path.extname(f)] || 'application/octet-stream' }); fs.createReadStream(f).pipe(res); }).listen(4107);
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--no-sandbox'] });
const pg = await b.newPage(); await pg.setViewport({ width: 1440, height: 900 });
const errs = []; pg.on('pageerror', (e) => errs.push(e.message));
await pg.goto('http://localhost:4107/', { waitUntil: 'networkidle2' });
await pg.evaluate(() => document.querySelector('.u-gallery-item').scrollIntoView({ block: 'center' }));
await new Promise((r) => setTimeout(r, 1500));
await pg.click('.u-gallery-item:nth-child(2)');
await new Promise((r) => setTimeout(r, 700));
const open1 = await pg.evaluate(() => document.querySelector('.lightbox .lightbox__count')?.textContent);
await pg.keyboard.press('ArrowRight');
const open2 = await pg.evaluate(() => document.querySelector('.lightbox .lightbox__count')?.textContent);
await pg.screenshot({ path: path.join(dist, '..', '.shots', 'lb.png') });
await pg.keyboard.press('Escape');
await new Promise((r) => setTimeout(r, 500));
const closed = await pg.evaluate(() => !document.querySelector('.lightbox'));
console.log(JSON.stringify({ open1, open2, closed, errs }));
await b.close(); srv.close();
