import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path'; import puppeteer from 'puppeteer-core';
const dist = path.resolve(import.meta.dirname, '..', 'dist');
const MIME = { '.html': 'text/html', '.css': 'text/css', '.js': 'text/javascript', '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml', '.webp': 'image/webp' };
const srv = http.createServer((req, res) => { const p = decodeURIComponent(req.url.split('?')[0]); let f = path.join(dist, p); if (!fs.existsSync(f) || fs.statSync(f).isDirectory()) { const i = path.join(f, 'index.html'); f = fs.existsSync(i) ? i : path.join(dist, 'index.html'); } res.writeHead(200, { 'content-type': MIME[path.extname(f)] || 'application/octet-stream' }); fs.createReadStream(f).pipe(res); }).listen(4105);
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--no-sandbox'] });
const [url, y, name] = process.argv.slice(2);
const pg = await b.newPage(); await pg.setViewport({ width: 1440, height: 900 });
await pg.goto('http://localhost:4105' + url, { waitUntil: 'networkidle2' });
await pg.evaluate(async (Y) => { for (let s = 0; s <= Y; s += 300) { window.scrollTo(0, s); await new Promise((r) => setTimeout(r, 150)); } }, Number(y));
await new Promise((r) => setTimeout(r, 1200));
const st = await pg.evaluate(() => ({ hidden: document.querySelectorAll('.mo:not(.mo-in)').length, total: document.querySelectorAll('.mo').length, h: document.documentElement.scrollHeight }));
console.log(JSON.stringify(st));
await pg.screenshot({ path: path.join(dist, '..', '.shots', name + '.png') });
await b.close(); srv.close();
