// Généré par scripts/convert.mjs
import { lazy } from 'react';

export const routes = [
  { path: "/", legacy: "index.html", Component: lazy(() => import('./pages/Home.jsx')) },
  { path: "/a-propos", legacy: "About.html", Component: lazy(() => import('./pages/About.jsx')) },
  { path: "/services", legacy: "Services.html", Component: lazy(() => import('./pages/Services.jsx')) },
  { path: "/contact", legacy: "Contact.html", Component: lazy(() => import('./pages/Contact.jsx')) },
  { path: "/services/alarme-incendie", legacy: "Alarme-incendie.html", Component: lazy(() => import('./pages/AlarmeIncendie.jsx')) },
  { path: "/services/automatisme-et-instrumentation", legacy: "Automatisme-et-instrumentation.html", Component: lazy(() => import('./pages/AutomatismeInstrumentation.jsx')) },
  { path: "/services/composants-hydrauliques", legacy: "Composants-hydrauliques.html", Component: lazy(() => import('./pages/ComposantsHydrauliques.jsx')) },
  { path: "/services/controleur-acces", legacy: "Controleur-acces.html", Component: lazy(() => import('./pages/ControleurAcces.jsx')) },
  { path: "/services/domotique", legacy: "Domotique.html", Component: lazy(() => import('./pages/Domotique.jsx')) },
  { path: "/services/electricite-industrielle", legacy: "Electricite-industrielle.html", Component: lazy(() => import('./pages/ElectriciteIndustrielle.jsx')) },
  { path: "/services/energie-solaire", legacy: "Energie-solaire.html", Component: lazy(() => import('./pages/EnergieSolaire.jsx')) },
  { path: "/services/maintenance", legacy: "Maintenance.html", Component: lazy(() => import('./pages/Maintenance.jsx')) },
  { path: "/services/materiel-electrique", legacy: "Materiel-electrique.html", Component: lazy(() => import('./pages/MaterielElectrique.jsx')) },
  { path: "/services/personnel-technique", legacy: "Personnel-technique.html", Component: lazy(() => import('./pages/PersonnelTechnique.jsx')) },
  { path: "/services/roulements-transmissions", legacy: "Roulements-transmissions.html", Component: lazy(() => import('./pages/RoulementsTransmissions.jsx')) },
  { path: "/services/video-surveillances", legacy: "Video-surveillances.html", Component: lazy(() => import('./pages/VideoSurveillances.jsx')) },
  { path: "/blog", legacy: "Blog.html", Component: lazy(() => import('./pages/Blog.jsx')) },
  { path: "/faq", legacy: "FAQ-Page.html", Component: lazy(() => import('./pages/Faq.jsx')) },
  { path: "/equipe", legacy: "Team.html", Component: lazy(() => import('./pages/Team.jsx')) },
  { path: "/landing", legacy: "Landing.html", Component: lazy(() => import('./pages/Landing.jsx')) },
  { path: "/maquette", legacy: "Untitled-2.html", Component: lazy(() => import('./pages/Maquette.jsx')) },
  { path: "/blog/articles", legacy: "blog/blog.html", Component: lazy(() => import('./pages/BlogArticles.jsx')) },
  { path: "/blog/automatisation-industrielle", legacy: "blog/automatisation-industrielle.html", Component: lazy(() => import('./pages/BlogAutomatisationIndustrielle.jsx')) },
  { path: "/blog/energie-solaire-ecole", legacy: "blog/energie-solaire-ecole.html", Component: lazy(() => import('./pages/BlogEnergieSolaireEcole.jsx')) },
  { path: "/blog/formation-technique", legacy: "blog/formation-technique.html", Component: lazy(() => import('./pages/BlogFormationTechnique.jsx')) },
  { path: "/blog/maintenance-preventive", legacy: "blog/maintenance-preventive.html", Component: lazy(() => import('./pages/BlogMaintenancePreventive.jsx')) },
  { path: "/blog/supervision-industrielle", legacy: "blog/supervision-industrielle.html", Component: lazy(() => import('./pages/BlogSupervisionIndustrielle.jsx')) },
  { path: "/blog/videosurveillance-pme", legacy: "blog/videosurveillance-pme.html", Component: lazy(() => import('./pages/BlogVideosurveillancePme.jsx')) },
  { path: "/recherche", legacy: "search/search.html", Component: lazy(() => import('./pages/Search.jsx')) },
];
